server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    error_page 401 /custom_401.html;
    location = /custom_401.html {
        root /usr/share/nginx/html;
        internal;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}

    # Evolveum: added for midPoint training, reverse proxies
     location /hris {
       proxy_pass      http://hris_demo:8000/hris;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
    #######      auth_basic             "Training environment - Restricted";
    #######      auth_basic_user_file   .htpasswd;
    }

    location /midpoint {
      proxy_pass      http://midpoint:8080/midpoint;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Authorization ""; # otherwise midPoint GUI has troubles with missing Basic authentication module for GUI
    }

    location /midpoint/ws {
      proxy_pass      http://midpoint:8080/midpoint/ws;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
###      proxy_set_header Authorization ""; # cannot be used, otherwise Studio has troubles with 401 error
    }

    location /midpoint/actuator {
      proxy_pass      http://midpoint:8080/midpoint/actuator;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
###      proxy_set_header Authorization ""; # cannot be used, otherwise curl has troubles with 401 error
    }

    location /phpldapadmin {
      proxy_pass      http://phpldapadmin/phpldapadmin;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
###      auth_basic             "Training environment - Restricted";
###      auth_basic_user_file   .htpasswd;
    }

    location /midpilot-smart-integration/health {
      proxy_pass      http://midpilot-smart-integration:8090/health;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
###      auth_basic             "Training environment - Restricted";
###      auth_basic_user_file   .htpasswd;
    }

    # End Evolveum
}
